shiny:
  image:
    repository: anaeldelorme/suivicollecteesea
    tag: v2.3.5
    pullPolicy: Always
  ingress:
    enabled: true
    hostname: collecteesea.lab.sspcloud.fr
  s3:
    enabled: true
    existingSecret: suivicollecteesea-s3
  resources: {}